title: My Jekyll Blog
email: your-email@example.com
description: >-
  Welcome to my awesome Jekyll blog hosted on GitHub Pages.
baseurl: "" # Keep it empty for GitHub Pages
url: "https://quartz-datageek.github.io" # Set your GitHub Pages URL

# Theme Settings
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-redirect-from

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
