title: My Jekyll Blog
email: your-email@example.com
description: >-
  Welcome to my awesome Jekyll blog hosted on GitHub Pages.
baseurl: "" # Keep it empty for GitHub Pages
url: "https://quartz-datageek.github.io" # Set your GitHub Pages URL

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-US"
title_separator: "-"
subtitle: ""
name: "Your Name"
repository: "quartz-datageek/quartz-datageek.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-redirect-from

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
